name: ttocc
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10.16
  - pip
  - numpy=1.26.4
  - scipy=1.15.2
  - pytorch=2.3.1
  - torchvision=0.15.2
  - torchaudio=2.3.1
  - pytorch-cuda=11.8
  - pyyaml
  - matplotlib
  - scikit-learn
  - pandas
  - h5py
  - tqdm
  - _libgcc_mutex
  - _openmp_mutex
  - blas
  - brotli-python
  - bzip2
  - ca-certificates
  - certifi
  - charset-normalizer
  - cuda
  - cuda-cccl
  - cuda-command-line-tools
  - cuda-compiler
  - cuda-cudart
  - cuda-cudart-dev
  - cuda-cuobjdump
  - cuda-cupti
  - cuda-cuxxfilt
  - cuda-driver-dev
  - cuda-gdb
  - cuda-libraries
  - cuda-libraries-dev
  - cuda-memcheck
  - cuda-nsight
  - cuda-nsight-compute
  - cuda-nvcc
  - cuda-nvdisasm
  - cuda-nvml-dev
  - cuda-nvprof
  - cuda-nvprune
  - cuda-nvrtc
  - cuda-nvrtc-dev
  - cuda-nvtx
  - cuda-nvvp
  - cuda-runtime
  - cuda-samples
  - cuda-sanitizer-api
  - cuda-toolkit
  - cuda-tools
  - cuda-version
  - cuda-visual-tools
  - dbus
  - expat
  - fontconfig
  - freetype
  - gds-tools
  - glib
  - glib-tools
  - gmp
  - gmpy2
  - icu
  - idna
  - intel-openmp
  - jinja2
  - jpeg
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libcublas
  - libcublas-dev
  - libcufft
  - libcufft-dev
  - libcufile
  - libcufile-dev
  - libcurand
  - libcurand-dev
  - libcusolver
  - libcusparse
  - libcusparse-dev
  - libdeflate
  - libffi
  - libgcc-ng
  - libglib
  - libgomp
  - libiconv
  - libjpeg-turbo
  - libnpp
  - libnpp-dev
  - libnvjpeg
  - libnvjpeg-dev
  - libpng
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libwebp-base
  - libxcb
  - libxkbcommon
  - libxml2
  - llvm-openmp
  - lz4-c
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - mpc
  - mpfr
  - mpmath
  - ncurses
  - networkx
  - nsight-compute
  - nspr
  - nss
  - numpy-base
  - openjpeg
  - openssl
  - pcre2
  - pysocks
  - readline
  - requests
  - setuptools
  - sqlite
  - sympy
  - tbb
  - tk
  - torchtriton
  - urllib3
  - wheel
  - xz
  - yaml
  - zlib
  - zstd
  - pip:
      - submodules/diff-gaussian-rasterization
      - submodules/diff-gaussian-rasterization-semantic
      - absl-py
      - addict
      - aiofiles
      - annotated-types
      - antlr4-python3-runtime
      - anyio
      - appdirs
      - asttokens
      - attrs
      - beautifulsoup4
      - black
      - blinker
      - cachetools
      - click
      - cloudpickle
      - coloredlogs
      - colorlog
      - comm
      - configargparse
      - contourpy
      - cycler
      - dash
      - decorator
      - descartes
      - detectron2==0.6
      - diff-gaussian-rasterization
      - diff-gaussian-rasterization-semantic
      - docstring-parser
      - einops==0.8.1
      - embreex
      - exceptiongroup
      - executing
      - fastapi
      - fastjsonschema
      - ffmpy
      - filelock
      - fire
      - flask
      - flatbuffers
      - fonttools
      - fsspec
      - future
      - fvcore
      - gdown
      - gradio
      - gradio-client
      - grpcio
      - h11
      - h5py
      - hdbscan
      - httpcore
      - httpx
      - huggingface-hub
      - humanfriendly
      - hydra-core
      - imageio
      - importlib-metadata
      - importlib-resources
      - iopath
      - ipdb
      - ipython
      - ipywidgets
      - itsdangerous
      - jedi
      - joblib
      - jsonschema
      - jsonschema-specifications
      - jupyter-core
      - jupyterlab-widgets
      - kiwisolver
      - lazy-loader
      - lxml
      - manifold3d
      - mapbox-earcut
      - markdown
      - markdown-it-py
      - markupsafe
      - matplotlib
      - matplotlib-inline
      - mdurl
      - msgspec
      - mypy-extensions
      - narwhals
      - nbformat
      - nest-asyncio
      - nodeenv
      - nuscenes-devkit
      - omegaconf
      - onnxruntime
      - open3d==0.19.0
      - opencv-python
      - orjson
      - packaging
      - pandas
      - panopticapi
      - parmap
      - parso
      - pathspec
      - pexpect
      - pillow
      - platformdirs
      - plotly
      - plyfile
      - portalocker
      - prompt-toolkit
      - protobuf
      - psutil
      - ptyprocess
      - pure-eval
      - pycocotools
      - pycollada
      - pydantic
      - pydantic-core
      - pydot
      - pydub
      - pygments
      - pyparsing
      - pyquaternion
      - python-dateutil
      - python-multipart
      - pytz
      - referencing
      - regex
      - retrying
      - rich
      - rpds-py
      - rtree
      - ruff
      - safehttpx
      - safetensors
      - scikit-image
      - scikit-learn
      - seaborn
      - semantic-version
      - shapely
      - shellingham
      - shtab
      - simple-knn
      - six
      - sniffio
      - soupsieve
      - stack-data
      - starlette
      - svg-path
      - tabulate
      - tensorboard
      - tensorboard-data-server
      - termcolor
      - threadpoolctl
      - tifffile
      - timm
      - toml
      - tomli
      - tomlkit
      - tqdm
      - traitlets
      - trimesh
      - typeguard
      - typer
      - typing-extensions
      - typing-inspection
      - tyro
      - tzdata
      - uvicorn
      - vhacdx
      - viser
      - wcwidth
      - websockets
      - werkzeug
      - widgetsnbextension
      - xxhash
      - yacs
      - yourdfpy
      - zipp
